name: Two Jobs in Parallel

on: [push]

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get Sorted Linux Environment
      run: env | sort

    - name: Run Multiline Echo
      run: |
        echo "This is just a"
        echo "Multiline Echo ; )"
  
  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get Sorted Windows Environment
      run: "Get-ChildItem Env: | Sort-Object Name"
