name: Python App - DockerHub Push

on: [push]

env:
  APPLICATION_NAME: app2

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Python environment
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'    
      uses: actions/setup-python@v1.1.1
      with:
        python-version: 3.8

    - name: Install requirements
      run: |
        cd python_app
        pip install --quiet --requirement requirements.txt

    - name: Lint code
      run: |
        cd python_app      
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 --disable=C0326 --disable=R1732 --disable=W1514 *.py

    - name: Run unit tests
      run: |
        cd python_app
        python -m unittest --verbose --failfast

  build_and_push_to_registry:
    needs: [lint]
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata from Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: leandromana/linkedin-learning-github-actions-python-app

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./python_app
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
