name: JAKR - keyword-releaser

on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Create a Release based on Keyword
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: leandro-mana/jakr@main
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
