name: JAKR - keyword-releaser

on: [push]

env:
  master: ${{ github.ref == 'refs/heads/main' }} || ${{ github.ref == 'refs/heads/master' }}

jobs:
  is_master:
    if: ${{master}} 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Create a Release based on Keyword
      uses: leandro-mana/jakr@feature/add-actions-definitions
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
